### ISSUE TITLE
Sort downloaded content through folders by artists and albums

### ISSUE THREAD

**Issue by guicattani** [TheWicklowWolf/SpotTube#2]
Would be nice to have the download to be automatically sorted into folders with a structure.

Currently it downloads to the folder and the name has that information, but it would be much better to have it automatically sorted.

**Comment by TheWicklowWolf** [comment]
The current setup downloads directly into a folder named after the playlist for simplicity.

I don't need the feature to sort by artist and album at the moment, but there's an old fork that had it: https://github.com/derdydancer/SpotTube.

If this feature is important to you, feel free to submit a PR to add it. I'd be happy to merge it - just make sure it's configurable via an environmental variable, with the default set to false.
