### ISSUE TITLE
credentials do not persist

### ISSUE THREAD

**Issue by Vansmak** [TheWicklowWolf/SpotTube#4]
Anytime a restart the container i have to reenter the credentials manually in the settings.  I have verified they are getting picked up by the container though when it runs

**Comment by TheWicklowWolf** [comment]
It sounds like there is a permission issue with the mount `- /path/to/config:/spottube/config`, preventing SpotTube from saving the config file. You’ll need to ensure that uid:gid 1000:1000 has the necessary permissions.

As an alternative, you can set the following configuration via environment variables:

```yaml
    environment:
      - spotify_client_id=abc
      - spotify_client_secret=123
      - thread_limit=1
```
