### ISSUE TITLE
Some downloads are failing

### ISSUE THREAD

**Issue by lillemets** [TheWicklowWolf/SpotTube#5]
Most of the songs in an entered playlist are successfully downloaded. However, about 1/10 random songs seem to fail with the message "Download Failed". Why does this happen and is there any way to fix this? I'd like to have complete playlists. The songs that fail are avaiable on Youtube Music so that can't be the reason.

**Comment by TheWicklowWolf** [comment]
Even if the songs are available on YouTube Music, download failures can still happen due to rate limiting, video restrictions, etc.
You’ll need to check the logs for more details and figure out what the issue is.

Best of luck with it.

**Comment by lillemets** [comment]
I now checked the logs and in my case all of the failed downloads did so for the same reason: "Requested format is not available". I wish there was something I could do about it but I guess not. Thanks anyway!
